### ISSUE TITLE
Can't install with ES 5.4

### ISSUE THREAD

**Issue by ijajmulani** [spinscale/elasticsearch-ingest-opennlp#11]
I have elastic search version 5.4.
I cant install plugin, there is no installation guide written for it.
@spinscale

**Comment by spinscale** [comment]
Indeed. I havent released it yet due to time constraints, you can however just build it manually, if you have to.

**Comment by ijajmulani** [comment]
Ok. Could you give me brief how to build it for ES 5.4 ? so I can build it manually.

**Comment by spinscale** [comment]
stated here in the README https://github.com/spinscale/elasticsearch-ingest-opennlp/#setup

**Comment by ijajmulani** [comment]
Hi @spinscale ,
I know this is not right place to ask such question. I am implementing search functionality in my project.
So I wanted to know how could I implement own entity model. 
eg. I have "car_make", "price" column in my table, so when user searches 
"**maruti suzuki under 2 lac**"
it has to recognize 
'maruti suzuki' => 'car_make' 
and '2 lac' => 'price'

Also could you please share your email id so I wanted to clear some doubts about my project.

I am using 
Elasticsearch and your plugin for natural language processing

**Comment by spinscale** [comment]
update the repo to 5.6 in the meantime
