### ISSUE TITLE
Get on opennlp pipeline returns empty results

### ISSUE THREAD

**Issue by VidhiSanghavi** [spinscale/elasticsearch-ingest-opennlp#13]
As suggested in the example configured a new pipeline and added data to it
But on doing get I am getting blank entity
{
"_index": "nlp-index",
"_type": "my-type",
"_id": "1",
"_version": 1,
"found": true,
"_source": {
"my_field": "Kobe Bryant was one of the best basketball players of all times. Not even Michael Jordan has ever scored 81 points in one game. Munich is really an awesome city, but New York is as well. Yesterday has been the hottest day of the year.",
"entities": {}
}
}

**Comment by spinscale** [comment]
please provide a full reproduction instead of just a snippet... also show that you actually installed the plugin on all nodes

**Comment by spinscale** [comment]
closing, no feedback
