### ISSUE TITLE
Allow multiple OpenNLP models to be executed for each field

### ISSUE THREAD

**Issue by LyndonArmitage** [spinscale/elasticsearch-ingest-opennlp#16]
As a potential future enhancement (assuming it is not already supported) it would be great if you could list multiple models to be run for each field.

For example I might have several models for finding names in various different languages like English, German, French etc. and be able to list them like so in the YAML:

```yaml
ingest.opennlp.model.file.persons: 
  - en-ner-persons.bin
  - de-ner-persons.bin
  - fr-ner-persons.bin
```

This shouldn't be a big change and would provide more flexibility to the plugin.
Currently I think you can achieve the same kind of effect using the [script](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/script-processor.html) processor and having multiple fields
 
I'd make a pull request but  I am not familiar with the plugin API.

**Comment by spinscale** [comment]
you could do

```
ingest.opennlp.model.file.persons_de: en-ner-persons.bin
ingest.opennlp.model.file.persons_en: en-ner-persons.bin
```

so this should be supported with the current syntax. I dont intend to support parsing a field with several models. Those should become several fields instead. It's gonna be super hard to find out which model actually was a hit afterwards (the french or the german one?)

**Comment by spinscale** [comment]
I am closing this one for now. If someone wants to come up with a PR, feel free to do so, but I intend to keep this plugin as small as possible and will not put too much work into this from a feature perspective - especially if it can be solved via existing ES functionality.
