### ISSUE TITLE
Unable to install plugin with ES 6.1.2

### ISSUE THREAD

**Issue by ksrikant** [spinscale/elasticsearch-ingest-opennlp#21]
Trying to install plugin with elasticsearch-plugin version 6.1.2 results in "ERROR: Unknown plugin "elasticsearch-ingest-opennlp/build/distributions/ingest-opennlp-6.1.2.1-SNAPSHOT.zip"

Gradle Version        : 4.4.1
OS Info               : Mac OS X 10.12.6 (x86_64)
JDK Version           : Oracle Corporation 1.8.0_151 [Java HotSpot(TM) 64-Bit Server VM 25.151-b12]

**Comment by spinscale** [comment]
can you please provide the full command you typed in trying to install the plugin? Is it possible you forgot the `file://` prefix?

**Comment by ksrikant** [comment]
Yes, that was the issue, i missed the file prefix. My fault, thanks.
