### ISSUE TITLE
Signing issue when building

### ISSUE THREAD

**Issue by Gradle999** [spinscale/elasticsearch-ingest-opennlp#22]
When I run 'gradle build', 'gradle clean build' or 'gradle clean check' I get the same build failure, concerning signArchives. Specifically the error is:

Execution failed for task ‘:signedArchives’. Cannot perform signing task :signedArchives because it has no configured signatory. 

Is this a known error or am I missing something that is required? I notice that some lines of code concerning signing tasks have been removed, could this be the cause?

**Comment by spinscale** [comment]
1. which gradle version are you using?
2. Do you have anything in `~/.gradle/gradle.properties`
3. Have you pulled the latest code? Which commit are you on?

Can you paste the full output in here? Also the output of `gradle tasks` please?

**Comment by Gradle999** [comment]
Gradle version 4.6, also tried with 4.1 and got the same error. 

I have a Gradle.properties file but haven’t touched or edited this.

Yes using the latest commit. 

I don’t have my machine with me at the moment, but the error message is: What went wrong:
Execution failed for task ':signArchives'.
Cannot perform signing task ':signArchives' because it has no configured signatory

**Comment by spinscale** [comment]
as I said, I would like to see the output of the whole run, plus the output of `gradle tasks` plus the output of `git show -q`

your `gradle.properties` file is empty I assume?

thanks!

**Comment by Gradle999** [comment]
Sorry for not getting back to you. I've managed to fix the signing issue by rebuilding the VM I'm installing it on and re-installing the dependencies. 

I have however encountered another issue when running `gradle clean check` to do with :test. Here is the output:

`> Configure project : 
=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  Gradle Version        : 4.6
  OS Info               : Linux 4.13.0-36-generic (amd64)
  JDK Version           : Oracle Corporation 9.0.4 [Java HotSpot(TM) 64-Bit Server VM 9.0.4+11]
  JAVA_HOME             : /usr/lib/jvm/java-9-oracle
  Random Testing Seed   : FE8864CB56BF055C

> Task :test 
==> Test Info: seed=AB21833D38A7AA08; jvms=3; suites=3

Suite: de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests
ERROR   0.00s J0 | OpenNlpProcessorTests (suite) <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: can not run elasticsearch as root
   >    at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:105)
   >    at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:80)
   >    at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:190)
   >    at java.base/java.lang.Class.forName0(Native Method)
   >    at java.base/java.lang.Class.forName(Class.java:375)
Completed [1/3] on J0 in 1.65s, 0 tests, 1 error <<< FAILURES!

Suite: de.spinscale.elasticsearch.ingest.opennlp.OpenNlpServiceTests
ERROR   0.00s J1 | OpenNlpServiceTests (suite) <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: can not run elasticsearch as root
   >    at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:105)
   >    at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:80)
   >    at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:190)
   >    at java.base/java.lang.Class.forName0(Native Method)
   >    at java.base/java.lang.Class.forName(Class.java:375)
Completed [2/3] on J1 in 1.69s, 0 tests, 1 error <<< FAILURES!

Suite: de.spinscale.elasticsearch.ingest.opennlp.OpenNlpThreadSafeTests
ERROR   0.00s J2 | OpenNlpThreadSafeTests (suite) <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: can not run elasticsearch as root
   >    at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:105)
   >    at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:80)
   >    at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:190)
   >    at java.base/java.lang.Class.forName0(Native Method)
   >    at java.base/java.lang.Class.forName(Class.java:375)
Completed [3/3] on J2 in 1.79s, 0 tests, 1 error <<< FAILURES!


> Task :test FAILED
Tests with failures:
  - de.spinscale.elasticsearch.ingest.opennlp.OpenNlpProcessorTests (suite)
  - de.spinscale.elasticsearch.ingest.opennlp.OpenNlpServiceTests (suite)
  - de.spinscale.elasticsearch.ingest.opennlp.OpenNlpThreadSafeTests (suite)

JUnit4 test failed, ant output was:
   [junit4] <JUnit4> says ¡Hola! Master seed: AB21833D38A7AA08
   [junit4] JVM J0:     1.06 ..     3.89 =     2.84s
   [junit4] JVM J1:     1.07 ..     4.12 =     3.05s
   [junit4] JVM J2:     0.83 ..     3.86 =     3.04s
   [junit4] Execution time total: 4.13 sec.
   [junit4] Tests summary: 3 suites, 0 tests, 3 suite-level errors



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were test failures: 3 suites, 0 tests, 3 suite-level errors [seed: AB21833D38A7AA08]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 20s
30 actionable tasks: 27 executed, 3 up-to-date
`

Any ideas on this?

**Comment by Gradle999** [comment]
Sorry for not getting back to you. I've managed to stop the signing issue by re-installing the dependencies on my VM, however I'm getting another Java error:

> Configure project : 
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.


FAILURE: Build failed with an exception.

* Where:
Build file '/home/ubuntu/elasticsearch-ingest-opennlp/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating root project 'ingest-opennlp'.
> Failed to apply plugin [id 'elasticsearch.esplugin']
   > JAVA_HOME must be set to build Elasticsearch

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s

`echo $JAVA_HOME` returns `/usr/lib/jvm/java-9-oracle` which is the correct directory for my Java.

Any ideas? Seen this before?

**Comment by spinscale** [comment]
can you run `env | grep JAVA_HOME` please?

Can you also show the output of  `ls -l /usr/lib/jvm/java-9-oracle` - are you sure this is a JDK and not an JRE?

**Comment by spinscale** [comment]
any update here?

**Comment by spinscale** [comment]
No feedback. Closing.
