### ISSUE TITLE
Java IO Exception while Installing

### ISSUE THREAD

**Issue by Javedayesha** [spinscale/elasticsearch-ingest-opennlp#24]
![screenshot from 2018-03-12 10-49-38](https://user-images.githubusercontent.com/32936808/37268061-c5ea6eb4-25e5-11e8-8783-0b3e44cde4c3.png)

**Comment by spinscale** [comment]
you have specified the wrong path on installation.. looks like you did not specify a drive, like `C:` or `D:`.

This is not a plugin issue. Also note, that you can just install the already provided zip file, see the correct URL in the README.

**Comment by Javedayesha** [comment]
Thanks
