### ISSUE TITLE
Entity extraction without indexing?

### ISSUE THREAD

**Issue by homerlex** [spinscale/elasticsearch-ingest-opennlp#26]
Is it possible to use this to do entity extraction on an arbitrary blurb of text without indexing said text?

The use case is we have a paragraph of text that we want to do some entity extraction on (pull out people name) but don't want that text stored in the index.

**Comment by spinscale** [comment]
you could use the [Simulate Pipeline API](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/simulate-pipeline-api.html) for this.

This is built into Elasticsearch, so does not require any changes in this plugin.
