### ISSUE TITLE
FAILURE: Build failed with an exception. Execution failed for task ':integTestRunner'.

### ISSUE THREAD

**Issue by mattiabaldari** [spinscale/elasticsearch-ingest-opennlp#28]
Hi,

I am trying to install this project, but with no luck.
I have a fresh new installed Ubuntu 18.10, updated and with java-11-openjdk-amd64 and gradle 4.10.2 installed. And the content of my $JAVA_HOME is the following:

`echo $JAVA_HOME`
`/usr/lib/jvm/java-11-openjdk-amd64/bin/`

Specified manually in the /etc/environment file. 
Starting from the situation described above I try to install the project, to do so I run the following commands:

`git clone https://github.com/bnafziger/elasticsearch-ingest-opennlp.git`
`cd path/to/elasticsearch-ingest-opennlp`
`gradle build`

But after the compiling part, it throws the following exception:
<img width="1042" alt="screenshot 2018-10-25 at 19 37 53" src="https://user-images.githubusercontent.com/13599910/47519289-89483800-d88d-11e8-84b8-accc8fcd878f.png">

If you have any solution would be really helpful.
Thank you

**Comment by mattiabaldari** [comment]
@spinscale no idea why this happens?

**Comment by spinscale** [comment]
please use the gradle wrapper instead of your local gradle installation and include the **full** log output in a gist. Thanks!

**Comment by mattiabaldari** [comment]
I'll try on a new Ubuntu instance and let you know. thanks

**Comment by mattiabaldari** [comment]
I tried on a fresh Ubuntu install and it works!
Thank you!

For who ends up on this ISSUE, **BE SURE** to have already installed ElasticSeach, I know can sound obvious, but in some tasks, like the one I am doing, you can forget the obvious parts.

To install it, just follow this guide: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-16-04

As a very last thing, in order to make the installation work pay attention to the Hardware requirements needed for your ElasticSeach installation, sometimes it can fail due to insufficient resources.

**Comment by spinscale** [comment]
You do **not** need Elasticsearch at all preinstalled in order to work with this plugin. Everything comes prebundled or is downloaded as part of gradle jobs.

Can you please explain why you think, that Elasticsearch is needed? Happy to sort out any confusions.

**Comment by mattiabaldari** [comment]
Hi @spinscale,

I wrote that because I wasn't able to make it work until elasticsearch was installed on my machine.
If you need I can try to install it again without elastic and see what is the outcome.

Bests

**Comment by spinscale** [comment]
thanks a ton for the offer! only retry, if you have the time. I'm fine as is, but still sure that you did something else in addition to installing Elasticsearch locally, that made this work on your machine (like installing the right java version for example).

**Comment by mattiabaldari** [comment]
Ok, so I have a new ubuntu installation, with nothing on it but your project in the download folder, unzipped. If I follow the readme file I should give the following command to install it:

bin/elasticsearch-plugin install https://github.com/spinscale/elasticsearch-ingest-opennlp/releases/download/6.5.0.1/ingest-opennlp-6.5.0.1.zip

but my system does not recognise this command. 
I'll leave it as it is, so maybe with your help I can figure out what I'm doing wrong

**Comment by spinscale** [comment]
this command assumes you are in the elasticsearch installation directory. This will not be fixed by installing elasticsearch globally. I think you may have changed that command after installing ES?

**Comment by mattiabaldari** [comment]
Ok! I understand now that the installation has to start from:

`./gradlew clean check`


Since in the README.md this was not on top, I though it was something to perform AFTER the installation. So... now I ran that command, nothing else before it, just a 
"sudo apt-get update & upgrade".

What I get is:

`ERROR: JAVA_HOME is not set and no 'java' command could be found in your path.`

It is safe to say I need to install JAVA first, any speecific version?
