### ISSUE TITLE
Download instructions for windows are not correct

### ISSUE THREAD

**Issue by stanuku** [spinscale/elasticsearch-ingest-opennlp#31]
```
If you are using windows, please use the following command

bin/ingest-opennlp/download-models.bat
```

Windows uses backward slashes "\" instead.
Also there is a path issue within the `download-models.bat`

```call "%~dp0elasticsearch-cli.bat" ^``` -> doesn't work (I had to hard code the path on my computer)

**Comment by spinscale** [comment]
Thanks for the report!

Can you possibly open a PR to fix it? I do not have a windows installation to test at the moment.

**Comment by dataanalyst4lyfe** [comment]
@stanuku - I'm running into the same error. How were you able to hard code the new directory, and not have the file overridden? I am running the `gradlew clean check` command, and the `download-models.bat` file gets overridden, so it keeps failing whenever I build it.
