### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by forchee** [spinscale/elasticsearch-ingest-opennlp#35]
I cloned the latest version and tried to build it using the shipped gradle wrapper (./gradlew). Any ideas why this would fail to build? Here is the trace:

$ ./gradlew
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/guest/elasticsearch-ingest-opennlp/build.gradle' line: 28

* What went wrong:
A problem occurred evaluating root project 'ingest-opennlp'.
> Failed to apply plugin [class 'org.elasticsearch.gradle.BuildPlugin']
   > Cannot set maxParallelForks to a value less than 1.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring root project 'ingest-opennlp'.
> Failed to notify project evaluation listener.
   > Must specify license and notice file for project :
   > Must specify license and notice file for project :
   > Must specify license and notice file for project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 35s

**Comment by spinscale** [comment]
can you share and properly format the **full** output of a run (best would be to put it in a gist). Also, can mention what operating system you are using?

Just to be sure: Is this a clean check out from the master branch with no changes?

**Comment by spinscale** [comment]
no response. closing.
