### ISSUE TITLE
How to add new models into the plugins

### ISSUE THREAD

**Issue by richylyq** [spinscale/elasticsearch-ingest-opennlp#36]
Hi,

I would like to check on how to add other models into the ingest-opennlp?

I am using elasticsearch 7.6.0 in docker and I am not sure on how to download the other models into the folder.

```
[root@5ea95291b711 ingest-opennlp]# ls
en-ner-dates.bin  en-ner-locations.bin  en-ner-persons.bin
[root@5ea95291b711 ingest-opennlp]# 
```

**Comment by spinscale** [comment]
you could call the plugin command in the docker container or volume mount those into your container, if you have created them manually. 

Hope that helps!
