### ISSUE TITLE
Support for OpenSearch

### ISSUE THREAD

**Issue by MysterionRise** [spinscale/elasticsearch-ingest-opennlp#39]
Is there any plans or intent to support plugins to be working on OpenSearch as well? Link - https://opensearch.org/

For newer version of course it will be difficult, but legacy versions based on 7.10.2 could have just minor change in order to support it as well. WDYT?

**Comment by spinscale** [comment]
Hey,

I haven't thought about this at all to be honest. Do you reckon that we could run the same integration tests as with Elasticsearch, that spin up an instance, install the plugin, run the YAML tests within the same repo or would it make sense to create a branch/fork for this?

**Comment by spinscale** [comment]
Seems there is a fork now at https://github.com/aparo/opensearch-ingest-opennlp

Closing this.
