### ISSUE TITLE
version 8.3.2

### ISSUE THREAD

**Issue by chminnaar** [spinscale/elasticsearch-ingest-opennlp#42]
When installing on Docker with Elasticsearch version 8.3.2, 
The command "bin/ingest-opennlp/download-models" are no longer available.

The last version I still could access was version 8.1.3.

Is there another way to install the NER models?

**Comment by spinscale** [comment]
You can just download them via curl... but that CLI tool has been removed inadverdently... I'll create a fix

**Comment by spinscale** [comment]
See https://github.com/spinscale/elasticsearch-ingest-opennlp/blob/main/build.gradle#L135-L141

**Comment by spinscale** [comment]
Closed by https://github.com/spinscale/elasticsearch-ingest-opennlp/commit/066fb2b7baf08335b36d3ffd3327be19188079e4
