### ISSUE TITLE
Should avoid duplicates

### ISSUE THREAD

**Issue by mkoertgen** [spinscale/elasticsearch-ingest-opennlp#5]
The openNLPfinder may extract duplicates on real data. This is ok if you part-of-speech tagging along with sentences. I think for this ingest plugin you typically don't want this.

Since NER is based on maximum entropy, this is probably not trivially to reproduce with small test data.
SImply duplicating entities on test data, makes the extractor typically skip the entity altogether.

So i introduced an interface, cf. PR #4 

Would be happy if this could be merged.

**Comment by spinscale** [comment]
Closed by 0870939a0c7cfb5e7724b5affb1d1fc0ef98569b
